
package mealplanner;

import java.util.Set;


public class AllergyWindow extends javax.swing.JFrame {

    private WindowManager _windowManager;

    /** Creates new form AllergyWindow */
    public AllergyWindow(WindowManager wm) {
        initComponents();
        _windowManager = wm;

        selectAllergies();
    }

    private void selectAllergies()
    {
        Set<Allergy> allergies = _windowManager.getUser().getAllergies();
        if(allergies.contains(Allergy.CORN))
            cornBox.setSelected(true);
        if(allergies.contains(Allergy.EGG))
            eggsBox.setSelected(true);
        if(allergies.contains(Allergy.GARLIC))
            garlicBox.setSelected(true);
        if(allergies.contains(Allergy.MILK))
            milkBox.setSelected(true);
        if(allergies.contains(Allergy.MSG))
            msgBox.setSelected(true);
        if(allergies.contains(Allergy.OAT))
            oatsBox.setSelected(true);
        if(allergies.contains(Allergy.PEANUT))
            peanutsBox.setSelected(true);
        if(allergies.contains(Allergy.SOY))
            soyBox.setSelected(true);
        if(allergies.contains(Allergy.NUT))
            treeNutsBox.setSelected(true);
        if(allergies.contains(Allergy.WHEAT))
            wheatBox.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel = new javax.swing.JLabel();
        cornBox = new javax.swing.JCheckBox();
        garlicBox = new javax.swing.JCheckBox();
        oatsBox = new javax.swing.JCheckBox();
        milkBox = new javax.swing.JCheckBox();
        peanutsBox = new javax.swing.JCheckBox();
        soyBox = new javax.swing.JCheckBox();
        treeNutsBox = new javax.swing.JCheckBox();
        wheatBox = new javax.swing.JCheckBox();
        eggsBox = new javax.swing.JCheckBox();
        msgBox = new javax.swing.JCheckBox();
        toPlannerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        warningLabel1 = new javax.swing.JLabel();
        warningLabel2 = new javax.swing.JLabel();
        warningLabel3 = new javax.swing.JLabel();
        warningLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instructionLabel.setText("Select your allergies below");

        cornBox.setText("Corn");

        garlicBox.setText("Garlic");

        oatsBox.setText("Oats");

        milkBox.setText("Milk");

        peanutsBox.setText("Peanuts");

        soyBox.setText("Soy");

        treeNutsBox.setText("Nuts (other)");

        wheatBox.setText("Wheat");

        eggsBox.setText("Eggs");

        msgBox.setText("MSG");

        toPlannerButton.setText("Go to Meal Planner");
        toPlannerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toPlannerButtonMouseClicked(evt);
            }
        });

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        warningLabel1.setText("Warning: By continuing to Meal Planner, you");

        warningLabel2.setText("acknowledge that you are aware that not all ");

        warningLabel3.setText("dishes containing allergens will be flagged");

        warningLabel4.setText("in this program.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cornBox)
                            .addComponent(garlicBox)
                            .addComponent(oatsBox)
                            .addComponent(milkBox)
                            .addComponent(peanutsBox)
                            .addComponent(backButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(msgBox)
                                    .addComponent(eggsBox)
                                    .addComponent(wheatBox)
                                    .addComponent(soyBox)
                                    .addComponent(treeNutsBox)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(toPlannerButton))))
                    .addComponent(instructionLabel)
                    .addComponent(warningLabel1)
                    .addComponent(warningLabel2)
                    .addComponent(warningLabel3)
                    .addComponent(warningLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cornBox)
                    .addComponent(soyBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(garlicBox)
                    .addComponent(treeNutsBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oatsBox)
                    .addComponent(wheatBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(milkBox)
                    .addComponent(eggsBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peanutsBox)
                    .addComponent(msgBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(toPlannerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        saveAllergies();
         _windowManager.getDatabase().updateUser(_windowManager.getUser());
        _windowManager.showEmailWindow();
    }//GEN-LAST:event_backButtonMouseClicked

    private void toPlannerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toPlannerButtonMouseClicked
        saveAllergies();
         _windowManager.getDatabase().updateUser(_windowManager.getUser());
        _windowManager.showPlannerMainWindow();
    }//GEN-LAST:event_toPlannerButtonMouseClicked

    private void saveAllergies()
    {
        if(cornBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.CORN);
        else
            _windowManager.getUser().removeAllergy(Allergy.CORN);
        if(eggsBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.EGG);
        else
            _windowManager.getUser().removeAllergy(Allergy.EGG);
        if(garlicBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.GARLIC);
        else
            _windowManager.getUser().removeAllergy(Allergy.GARLIC);
        if(milkBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.MILK);
        else
            _windowManager.getUser().removeAllergy(Allergy.MILK);
        if(msgBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.MSG);
        else
            _windowManager.getUser().removeAllergy(Allergy.MSG);
        if(oatsBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.OAT);
        else
            _windowManager.getUser().removeAllergy(Allergy.OAT);
        if(peanutsBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.PEANUT);
        else
            _windowManager.getUser().removeAllergy(Allergy.PEANUT);
        if(soyBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.SOY);
        else
            _windowManager.getUser().removeAllergy(Allergy.SOY);
        if(treeNutsBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.NUT);
        else
            _windowManager.getUser().removeAllergy(Allergy.NUT);
        if(wheatBox.isSelected())
            _windowManager.getUser().addAllergy(Allergy.WHEAT);
        else
            _windowManager.getUser().removeAllergy(Allergy.WHEAT);

        //save user to database
        _windowManager.getDatabase().updateUser(_windowManager.getUser());
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox cornBox;
    private javax.swing.JCheckBox eggsBox;
    private javax.swing.JCheckBox garlicBox;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JCheckBox milkBox;
    private javax.swing.JCheckBox msgBox;
    private javax.swing.JCheckBox oatsBox;
    private javax.swing.JCheckBox peanutsBox;
    private javax.swing.JCheckBox soyBox;
    private javax.swing.JButton toPlannerButton;
    private javax.swing.JCheckBox treeNutsBox;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel warningLabel2;
    private javax.swing.JLabel warningLabel3;
    private javax.swing.JLabel warningLabel4;
    private javax.swing.JCheckBox wheatBox;
    // End of variables declaration//GEN-END:variables

}
