

package mealplanner;

import java.awt.FlowLayout;

public class EmailWindow extends javax.swing.JFrame {

    private WindowManager _windowManager;

    /** Creates new form EmailWindow */
    public EmailWindow(WindowManager wm) {
        _windowManager = wm;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        confirmEmailLabel = new javax.swing.JLabel();
        confirmEmailField = new javax.swing.JTextField();
        signUpButton = new javax.swing.JButton();
        unsubscribeButton = new javax.swing.JButton();
        notificationLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        instructionLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instructionLabel1.setText("To sign up for email notifications of when your favorite");

        emailLabel.setText("Email:");

        confirmEmailLabel.setText("Confirm email:");

        signUpButton.setText("Sign me up!");
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });

        unsubscribeButton.setText("Unsubscribe");
        unsubscribeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unsubscribeButtonMouseClicked(evt);
            }
        });

        notificationLabel.setForeground(java.awt.Color.red);
        notificationLabel.setText("Error: email addresses do not match!");
        notificationLabel.setVisible(false);

        nextButton.setText("Next");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });

        instructionLabel2.setText("dishes are on the menu, enter your email below.");

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificationLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmEmailLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(instructionLabel2)
                    .addComponent(instructionLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unsubscribeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signUpButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(nextButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel2)
                .addGap(39, 39, 39)
                .addComponent(notificationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmEmailLabel)
                    .addComponent(confirmEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsubscribeButton)
                    .addComponent(signUpButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        String email = emailField.getText();
        String confirmation = confirmEmailField.getText();
        if(email.isEmpty())
        {
            notificationLabel.setText("Error: no email address was entered!");
            notificationLabel.setVisible(true);
        }
        else if(confirmation.isEmpty())
        {
            notificationLabel.setText("Error: email address was not confirmed!");
            notificationLabel.setVisible(true);
        }
        else if(email.equals(confirmation))
        {
            _windowManager.getUser().setEmail(email);
            _windowManager.getDatabase().updateUser(_windowManager.getUser());
            notificationLabel.setText("You've been signed up!");
            notificationLabel.setVisible(true);
        }
        else
        {
            notificationLabel.setText("Error: email addresses do not match!");
            notificationLabel.setVisible(true);
        }
    }//GEN-LAST:event_signUpButtonMouseClicked

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        _windowManager.showAllergyWindow();
    }//GEN-LAST:event_nextButtonMouseClicked

    private void unsubscribeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unsubscribeButtonMouseClicked
        _windowManager.getUser().setEmail("");
        _windowManager.getDatabase().updateUser(_windowManager.getUser());
        notificationLabel.setText("You've been unsubscribed.");
        notificationLabel.setVisible(true);
    }//GEN-LAST:event_unsubscribeButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        _windowManager.showLikeDislikeWindow();
    }//GEN-LAST:event_backButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField confirmEmailField;
    private javax.swing.JLabel confirmEmailLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel instructionLabel1;
    private javax.swing.JLabel instructionLabel2;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JButton unsubscribeButton;
    // End of variables declaration//GEN-END:variables

}
