/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LikeDislikeWindow.java
 *
 * Created on Apr 10, 2012, 3:21:03 PM
 */

package mealplanner;

import java.awt.CheckboxGroup;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.Checkbox;
import java.util.HashSet;
import javax.swing.JLabel;
import javax.swing.JViewport;

/**
 *
 * @author seadams
 */
public class LikeDislikeWindow extends javax.swing.JFrame {

    private WindowManager _windowManager;

    /** Creates new form LikeDislikeWindow */
    public LikeDislikeWindow(WindowManager wm) {
        initComponents();
        _windowManager = wm;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel = new javax.swing.JLabel();
        dishLabel = new javax.swing.JLabel();
        dishField = new javax.swing.JTextField();
        searchResultsLabel = new javax.swing.JLabel();
        resultDisplay = new javax.swing.JScrollPane();
        clearDislikesButton = new javax.swing.JButton();
        clearLikesButton = new javax.swing.JButton();
        toAllergiesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instructionLabel.setText("Search for and enter you likes and dislikes below");
        instructionLabel.setAlignmentY(this.CENTER_ALIGNMENT);

        dishLabel.setText("Dish:");

        dishField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dishFieldKeyTyped(evt);
            }
        });

        searchResultsLabel.setText("Search results:");

        clearDislikesButton.setText("Clear all dislikes");
        clearDislikesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearDislikesButtonMouseClicked(evt);
            }
        });

        clearLikesButton.setText("Clear all likes");
        clearLikesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearLikesButtonMouseClicked(evt);
            }
        });

        toAllergiesButton.setText("Go to Allergy Preferences");
        toAllergiesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toAllergiesButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dishLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dishField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(instructionLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchResultsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clearLikesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearDislikesButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(410, Short.MAX_VALUE)
                        .addComponent(toAllergiesButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dishLabel)
                    .addComponent(dishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchResultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearDislikesButton)
                    .addComponent(clearLikesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toAllergiesButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dishFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dishFieldKeyTyped
        String input = dishField.getText().toUpperCase();

        HashSet<Dish> dishes = _windowManager.getDatabase().getDishes(input);
        //display the dishes in the resultDisplay        
        GridLayout layout = new GridLayout(0,1);
        Panel p = new Panel(layout);
        HashSet<String> names = new HashSet<String>();
        for(Dish dish: dishes)
        {
            if(!names.contains(dish.getName())) {
              names.add(dish.getName());
              Component c = toComponent(dish.getName());
              p.add(c);
            }
        }
        //show the new components
        resultDisplay.setViewportView(p);
        resultDisplay.validate();
}//GEN-LAST:event_dishFieldKeyTyped

    private void clearLikesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearLikesButtonMouseClicked
        _windowManager._user.clearLikes(); //clears the user object's likes
        //update the window to show the likes have been cleared
         JViewport v = resultDisplay.getViewport();
        Component [] c = v.getComponents(); //returns the panel containing panels made by toComponent()
        Panel topLevelPanel = (Panel) c[0];
        for(int i = 0; i < topLevelPanel.getComponentCount(); i++)
        {
            Panel p = (Panel) topLevelPanel.getComponent(i);
            Checkbox likeBox = (Checkbox) p.getComponent(1);
            Checkbox noPrefBox = (Checkbox) p.getComponent(3);
            if(likeBox.getState())
            {
                likeBox.setState(false);
                noPrefBox.setState(true);
            }
        }

    }//GEN-LAST:event_clearLikesButtonMouseClicked

    private void clearDislikesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDislikesButtonMouseClicked
        _windowManager._user.clearDislikes(); //clears the user object's dislikes
        //update the window to show the dislikes have been cleared
         JViewport v = resultDisplay.getViewport();
        Component [] c = v.getComponents(); //returns the panel containing panels made by toComponent()
        Panel topLevelPanel = (Panel) c[0];
        for(int i = 0; i < topLevelPanel.getComponentCount(); i++)
        {
            Panel p = (Panel) topLevelPanel.getComponent(i);
            Checkbox dislikeBox = (Checkbox) p.getComponent(2);
            Checkbox noPrefBox = (Checkbox) p.getComponent(3);
            if(dislikeBox.getState())
            {
                dislikeBox.setState(false);
                noPrefBox.setState(true);
            }
        }
    }//GEN-LAST:event_clearDislikesButtonMouseClicked

    private void toAllergiesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAllergiesButtonMouseClicked
        _windowManager.getDatabase().updateUser(_windowManager._user);
        _windowManager.showAllergyWindow();
    }//GEN-LAST:event_toAllergiesButtonMouseClicked

    private Component toComponent(String dish)
    {
        JLabel l = new JLabel();
        l.setText(dish);
        CheckboxGroup group = new CheckboxGroup();
        Checkbox likeBox = new Checkbox("Like", false, group);
        Checkbox dislikeBox = new Checkbox("Dislike", false, group);
        Checkbox noPreferenceBox = new Checkbox("No preference", true, group);
        GridLayout layout = new GridLayout(1,3); //1 row, 3 columns
        Panel p = new Panel(layout);
        p.add(l);
        p.add(likeBox);
        p.add(dislikeBox);
        p.add(noPreferenceBox);
        if(_windowManager._user.getLikes().contains(dish))
        {
            likeBox.setState(true);
        }
        else if(_windowManager._user.getDislikes().contains(dish))
        {
            dislikeBox.setState(true);
        }

        likeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                likeBoxClicked(evt);
            }
        });

        dislikeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dislikeBoxClicked(evt);
            }
        });

        noPreferenceBox.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noPreferenceBoxClicked(evt);
            }
        });
        
        return p;
    }

    private void likeBoxClicked(java.awt.event.MouseEvent evt)
    {
        Panel p = (Panel) evt.getComponent().getParent();
        JLabel l = (JLabel) p.getComponent(0);
        String dishName = l.getText();
        _windowManager._user.removeDislike(dishName); //must remove from dislikes before adding to likes bcs of implementation in UserAccount
        _windowManager._user.addLike(dishName);
    }

    private void dislikeBoxClicked(java.awt.event.MouseEvent evt)
    {
        Panel p = (Panel) evt.getComponent().getParent();
        JLabel l = (JLabel) p.getComponent(0);
        String dishName = l.getText();
        _windowManager._user.removeLike(dishName);//must remove from likes before adding to likes bcs of implementation in UserAccount
        _windowManager._user.addDislike(dishName);
    }

    private void noPreferenceBoxClicked(java.awt.event.MouseEvent evt)
    {
        Panel p = (Panel) evt.getComponent().getParent();
        JLabel l = (JLabel) p.getComponent(0);
        String dishName = l.getText();
        _windowManager._user.removeDislike(dishName);
        _windowManager._user.removeLike(dishName);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearDislikesButton;
    private javax.swing.JButton clearLikesButton;
    private javax.swing.JTextField dishField;
    private javax.swing.JLabel dishLabel;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JScrollPane resultDisplay;
    private javax.swing.JLabel searchResultsLabel;
    private javax.swing.JButton toAllergiesButton;
    // End of variables declaration//GEN-END:variables

}
