/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginWindow.java
 *
 * Created on Apr 9, 2012, 6:21:27 PM
 */

package mealplanner;

import java.awt.Cursor;
import java.awt.event.KeyEvent;

/**
 *
 * @author seadams
 */
public class LoginWindow extends javax.swing.JFrame {

    private WindowManager _windowManager;

    /** Creates new form LoginWindow */
    public LoginWindow(WindowManager wm) {
        initComponents();
        _windowManager = wm;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        newAccountButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meal Planner - Login");

        logInLabel.setText("Log in to Meal Planner!");

        usernameLabel.setText("Username:");

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        passwordLabel.setText("Password:");

        loginButton.setText("Log in");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        newAccountButton.setText("Create new account");
        newAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newAccountButtonMouseClicked(evt);
            }
        });

        errorLabel.setForeground(java.awt.Color.red);
        errorLabel.setText("Invalid username or password.");
        errorLabel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newAccountButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(usernameLabel)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(passwordLabel)
                                    .addGap(22, 22, 22)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameField)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(errorLabel)
                    .addComponent(logInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logInLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(newAccountButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newAccountButtonMouseClicked
         _windowManager.showNewAccountWindow();
   }//GEN-LAST:event_newAccountButtonMouseClicked


//this can be (and is) called with evt as null because evt is not used.
    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        String username = usernameField.getText();
        if(username.isEmpty())
        {
            errorLabel.setVisible(true);
            return;
        }
        char[] password = passwordField.getPassword();
        if(password.length == 0)
        {
            errorLabel.setVisible(true);
            return;
        }
        String passwordString = "";
        for(int i = 0; i < password.length; i++)
        {
            passwordString = passwordString + password[i];
        }
        UserAccount account = new UserAccount(username, SHAHash.getHash(passwordString));
        if(_windowManager.getDatabase().getUser(account).isValid())
         {
           _windowManager.setUser((UserAccount) _windowManager.getDatabase().getUser(account));

           //update database if necessary
            java.util.Calendar now = java.util.Calendar.getInstance();
            java.util.Calendar dbDate = _windowManager.getDatabase().getCurrentDate();
            int days = now.get(java.util.Calendar.DAY_OF_YEAR) - dbDate.get(java.util.Calendar.DAY_OF_YEAR);
            if(days > 0){
                becomeUpdatingWindow();
                _windowManager.getDatabase().update();
                Emailer emailer = new Emailer();
                emailer.sendEmail(_windowManager.getUser().getEmail(), _windowManager.getUser().getLikes());
            }

           _windowManager.showPlannerMainWindow();
         }
         else
           errorLabel.setVisible(true);

    }//GEN-LAST:event_loginButtonMouseClicked

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButtonMouseClicked(null);
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void hideAll()
    {
        errorLabel.setVisible(false);
        logInLabel.setVisible(false);
        newAccountButton.setVisible(false);
        passwordField.setVisible(false);
        passwordLabel.setVisible(false);
        usernameField.setVisible(false);
        usernameLabel.setVisible(false);
    }

    private void becomeUpdatingWindow()
    {
        hideAll();
        setTitle("Meal Planner - Updating");
        logInLabel.setText("Please wait while we retrieve the menus.");
        logInLabel.setVisible(true);
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.paint(this.getGraphics());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton newAccountButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
