/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newAccountWindow.java
 *
 * Created on Apr 9, 2012, 6:22:53 PM
 */

package mealplanner;


/**
 *
 * @author seadams
 */
public class NewAccountWindow extends javax.swing.JFrame {

    private WindowManager _windowManager;

    /** Creates new form newAccountWindow */
    public NewAccountWindow(WindowManager wm) {
        initComponents();
        _windowManager = wm;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goToLoginButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        alreadyUserLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmLabel = new javax.swing.JLabel();
        confirmField = new javax.swing.JPasswordField();
        createAccountButton = new javax.swing.JButton();
        usernameError = new javax.swing.JLabel();
        noPasswordError = new javax.swing.JLabel();
        notConfirmedError = new javax.swing.JLabel();
        confirmationMatchError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meal Planner - Create Account");

        goToLoginButton.setText("Log in");
        goToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToLoginButtonMouseClicked(evt);
            }
        });

        welcomeLabel.setText("Get started with Meal Planner!");

        alreadyUserLabel.setText("Already a user?");

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        confirmLabel.setText("Confirm Password:");

        createAccountButton.setText("Create Account");
        createAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountButtonMouseClicked(evt);
            }
        });

        usernameError.setForeground(java.awt.Color.red);
        usernameError.setText("Error: No username was entered!");
        usernameError.setVisible(false);

        noPasswordError.setForeground(java.awt.Color.red);
        noPasswordError.setText("Error: No password was entered!");
        noPasswordError.setVisible(false);

        notConfirmedError.setForeground(java.awt.Color.red);
        notConfirmedError.setText("Error: Password was not confirmed!");
        notConfirmedError.setVisible(false);

        confirmationMatchError.setForeground(java.awt.Color.red);
        confirmationMatchError.setText("Error: Password and confirmation do not match!");
        confirmationMatchError.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameError)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goToLoginButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alreadyUserLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmLabel)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmField)
                    .addComponent(passwordField)
                    .addComponent(usernameField)
                    .addComponent(createAccountButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notConfirmedError)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noPasswordError)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmationMatchError)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(11, 11, 11)
                .addComponent(usernameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noPasswordError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notConfirmedError)
                .addGap(4, 4, 4)
                .addComponent(confirmationMatchError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmLabel))
                .addGap(18, 18, 18)
                .addComponent(createAccountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(alreadyUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goToLoginButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLoginButtonMouseClicked
       _windowManager.showLoginWindow();
    }//GEN-LAST:event_goToLoginButtonMouseClicked

    private void createAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountButtonMouseClicked
        //hide all error messages and then display them as needed
        usernameError.setVisible(false);
        noPasswordError.setVisible(false);
        notConfirmedError.setVisible(false);
        confirmationMatchError.setVisible(false);
        boolean createAccount = true;
        String username = usernameField.getText();
        if(username.isEmpty())
        {
            usernameError.setVisible(true);
            createAccount = false;
        }
        char[] password = passwordField.getPassword();
        if(password.length == 0)
        {
            noPasswordError.setVisible(true);
            createAccount = false;
        }
        char[] confirmation = confirmField.getPassword();
        if(confirmation.length == 0)
        {
            notConfirmedError.setVisible(true);
            return; //we don't need to check for any more errors
        }
        boolean passwordsMatch = true;
        if(password.length != confirmation.length)
            passwordsMatch = false;
        else
        {
            for(int i = 0; i < password.length; i++)
            {
                if(password[i] != confirmation[i])
                {
                    passwordsMatch = false;
                    break;
                }
            }
        }
        if(passwordsMatch)
        {
            if(createAccount)
            {
                String passwordString = "";
                for(int i = 0; i < password.length; i++)
                {
                    passwordString = passwordString + password[i];
                }
                _windowManager._user = new UserAccount(username, passwordString);
                _windowManager.getDatabase().addUser(_windowManager._user);
                _windowManager.showLikeDislikeWindow();
            }
        }
        else
        { //the passwords do not match
            confirmationMatchError.setVisible(true);
        }
    }//GEN-LAST:event_createAccountButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyUserLabel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JLabel confirmationMatchError;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton goToLoginButton;
    private javax.swing.JLabel noPasswordError;
    private javax.swing.JLabel notConfirmedError;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameError;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

}
